name: 12 - Control de flujo - matriz
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      # Desactivamos fail-fast:  Para evitar que si falla un step se pare
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [18, 20]
        # exclude:
        # - os: ubuntu-22.04
        #   version: 20
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
        # Provocamos un error para la version de ubuntu 22.04 y node 20
        # continue-on-error :Si existe un falla sigue con el despliegue
        continue-on-error: false
      - run: npm ci
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: despliegue
        run: echo "Desplegando en AWS..." 