name: 13 - Control de flujo - funciones
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        version: [18, 20]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
      - run: npm test
      - name: Todo OK
        if: ${{ success() }}
        run: echo "Se ve si pasos anteriores han ido OK"
      - name: Tenemos un problema
        if: ${{ failure() }}
        run: echo "Se ve si el paso anterior falla"
      - name: Esto lo haces siempre
        if: ${{ always() }}
        run: echo "Se ve siempre. Aunque se cancele el workflow"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: despliegue
        run: echo "Desplegando en AWS..." 