name: 19 - Github token - 2025
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  prueba-permisos:
    name: Probar permisos
    permissions: 
        contents: read
        issues: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Retrieve issues via github cli
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh issue list
    - name: Retrieve issues via HTTP
      shell: bash
      run: |
        curl https://api.github.com/repos/${{ github.repository }}/issues \
        -H 'authorization: Bearer ${{ github.token }}' \
        -H 'content-type: application/json'